apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: $deploymentName
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $appLabel
    spec:
      containers:
        - name: exampleup
          image: localhost:5000/markwatsonatx/exampleup:latest
          volumeMounts:
            - mountPath: "/var/lib/docker"
              name: docker-storage
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: EXUP_STORAGE_DRIVER
            value: "aufs"
          - name: EXUP_LOG_PORT
            value: "$logPort"
          - name: EXUP_EDITOR_PORT
            value: "$editorPort"
          - name: EXUP_PROXY_PORT
            value: "$proxyPort"
          - name: EXUP_GIT_REPO
            value: "$gitRepo"
      volumes:
        - name: docker-storage
          persistentVolumeClaim:
            claimName: $pvcName
      terminationGracePeriodSeconds: 10